### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by SkyBulk** [anthony-fdez/notedpp#63]
it's a very interesting project!

Would you consider adding a license to this repository to specify under which terms this code can be used?

**Comment by anthony-fdez** [comment]
@SkyBulk hey man its really nice of you to ask about the license. I just added an MIT license, do with my bad code anything you want haha

**Comment by SkyBulk** [comment]
thanks mate, and I would say code isn't a big deal. I Prefer to focus on a solution that solves a problem rather than how fancy our code is.

**Comment by anthony-fdez** [comment]
I like the way you think man. If we truly wanted to write the best code possible we would never build anything!
